{
 "title": "Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   },
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "text",
   "description": "Cluster name",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1 style=\"color:#299c46;\">$cluster</h1></center>"
   },
   "content": "<center><h2>$cluster</h1></center>",
   "targets": [
    {
     "expr": "min(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "Cluster size",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "stat",
   "description": "Namespace stop_writes flag",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "stat",
   "description": "Total migration partitions remaining (transmit + receive)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) + sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Aerospike Version",
   "type": "stat",
   "description": "Build version",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Alert count",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Clock Skew Stop Writes",
   "type": "stat",
   "description": "Namespace clock_skew_stop_writes flag",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Unavailable / Dead Partitions",
   "type": "stat",
   "description": "Dead Partitions in an strong consistent namespace",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_unavailable_partitions{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Unavailable Partitions"
    },
    {
     "expr": "sum(aerospike_namespace_dead_partitions{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Dead Paritions"
    }
   ]
  },
  { "title": "Node Statstics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Client Connections",
   "type": "graph",
   "description": "Client connection count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "graph",
   "description": "Cluster size (cluster_size)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_cluster_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Resources (Memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active Heap Memory",
   "type": "graph",
   "description": "Amount of memory in in-use pages (heap_active_kbytes)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_active_kbytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Allocated Heap Memory",
   "type": "graph",
   "description": "Heap allocated memory (heap_allocated_kbytes)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_allocated_kbytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mapped Memory",
   "type": "graph",
   "description": "Heap mapped memory (heap_mapped_kbytes)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_mapped_kbytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap Efficiency",
   "type": "graph",
   "description": "Heap efficiency % (heap_efficiency_pct)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_heap_efficiency_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Free System Memory",
   "type": "graph",
   "description": "Percentage of free system memory available",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_system_free_mem_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Resources (CPU)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "ASD CPU usage",
   "type": "graph",
   "description": "Percentage of CPU usage by the asd process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_process_cpu_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "graph",
   "description": "Percentage of CPU usage by all running processes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_system_total_cpu_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Kernel mode CPU usage",
   "type": "graph",
   "description": "Percentage of CPU usage by processes running in kernel mode.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_system_kernel_cpu_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "User mode CPU usage",
   "type": "graph",
   "description": "Percentage of CPU usage by processes running in user mode.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_system_user_cpu_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Throughput (Batch)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<br/>\n<center><h2 style=\"color:#D11372;\">See <a href=\"/d/zGcUKcDZz/namespace-vitew\">Namespace View dashboard</a> for namespace and transaction type specific TPS and Latency</h2></center>"
   },
   "content": " \n\n### For namespace specific throughput please see the [Namespace View dashboard](/d/zGcUKcDZz/namespace-view)."
  },
  {
   "title": "Batch Reads (TPS)",
   "type": "graph",
   "description": "Batch Index TPS shows per-second average rate of increase in\n\n1. Total = batch_index_complete\n2. Successful = batch_index_complete - (batch_index_timeout + batch_index_error)\n3. Timeout = batch_index_timeout\n4. Error = batch_index_error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_batch_index_complete{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Total"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_complete{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) - (rate(aerospike_node_stats_batch_index_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_node_stats_batch_index_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
     "legendFormat": "{{service}}: Successful"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_timeout{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Timeout"
    },
    {
     "expr": "rate(aerospike_node_stats_batch_index_error{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}: Error"
    }
   ]
  }
 ]
}