{
 "title": "Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   },
   { "name": "latencytimeunit", "label": "Latency Time Unit", "query": "metrics(aerospike_latencies_)" },
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "node" },
  {
   "title": "Status",
   "type": "stat",
   "description": "Exporter and Aerospike node status",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$service|$^\"})",
     "legendFormat": "Exporter"
    },
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}",
     "legendFormat": "Aerospike"
    }
   ]
  },
  {
   "title": "Node Namespace Stats",
   "type": "stat",
   "description": "Total records and tombstones count",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Records"
    },
    {
     "expr": "sum(aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Tomstones"
    }
   ]
  },
  {
   "title": "Node Namespace Stats",
   "type": "stat",
   "description": "Total namespace memory size\nTotal namespace memory used\nTotal namespace device size\nTotal namespace device used",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Total Memory Size"
    },
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(aerospike_namespace_device_total_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Total Device Size"
    },
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Device Used"
    },
    {
     "expr": "sum(aerospike_namespace_pmem_total_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Total PMEM Size"
    },
    {
     "expr": "sum(aerospike_namespace_pmem_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "PMEM Used"
    }
   ]
  },
  {
   "title": "Latency: UDF / sec",
   "type": "graph",
   "description": "UDF transactions per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_udf_${latencytimeunit}_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "avg(aerospike_latencies_udf_${latencytimeunit}_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Alert count",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Client/Heartbeat/Fabric connections count",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}",
     "legendFormat": "Client"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}",
     "legendFormat": "Heartbeat"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}",
     "legendFormat": "Fabric"
    }
   ]
  },
  {
   "title": "Node Namespace Stats",
   "type": "gauge",
   "description": "Minimum of the Namespaces' Memory/Device Free Percentage",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_namespace_memory_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "min(aerospike_namespace_device_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Device Free"
    },
    {
     "expr": "min(aerospike_namespace_pmem_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "PMEM Free"
    }
   ]
  },
  {
   "title": "Latency: Reads / sec",
   "type": "graph",
   "description": "Reads per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_read_${latencytimeunit}_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "avg(aerospike_latencies_read_${latencytimeunit}_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Latency: Writes / sec",
   "type": "graph",
   "description": "Writes per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_write_${latencytimeunit}_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "avg(aerospike_latencies_write_${latencytimeunit}_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Latency: Proxies / sec",
   "type": "graph",
   "description": "Proxies per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_proxy_${latencytimeunit}_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "avg(aerospike_latencies_proxy_${latencytimeunit}_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Latency: Query / sec",
   "type": "graph",
   "description": "Queries per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_latencies_query_${latencytimeunit}_bucket{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "avg(aerospike_latencies_query_${latencytimeunit}_count{job=\"aerospike\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Client connections, fabric connections and heartbeat connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Client Connections"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Fabric Connections"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Heartbeat Connections"
    }
   ]
  },
  {
   "title": "Migrations (Partitions Remaining)",
   "type": "graph",
   "description": "Migrations remaining migrate_tx_partitions_remaining (transmit), migrate_rx_partitions_remaining (receive)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Incoming Partitions Remaining"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Outgoing Partitions Remaining"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "description": "Master objects, prole objects and tombstones",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Master"
    },
    {
     "expr": "aerospike_namespace_prole_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Prole"
    },
    {
     "expr": "aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Tombstones"
    }
   ]
  }
 ]
}