{
 "title": "XDR View (Aerospike 5.0+ only)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "dc",
    "label": "DC",
    "query": "label_values(aerospike_xdr_lap_us{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },dc)"
   },
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XDR Statistics Summary",
   "type": "stat",
   "description": "Total Throughput (sum across all namespaces and all DCs)\n\nAverage XDR Lag\n\nAverage Ship Latency\n\nAverage Lap us (Time taken to process records across partitions in one lap)\n\nTotal recoveries pending\n\nTotal In Progress\n\nTotal In Queue",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_xdr_throughput{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total Throughput"
    },
    {
     "expr": "avg(aerospike_xdr_lag{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Lag"
    },
    {
     "expr": "avg(aerospike_xdr_latency_ms{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Ship Latency"
    },
    {
     "expr": "avg(aerospike_xdr_lap_us{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Lap us"
    },
    {
     "expr": "sum(aerospike_xdr_recoveries_pending{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total Recoveries Pending"
    },
    {
     "expr": "sum(aerospike_xdr_in_progress{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total In Progress"
    },
    {
     "expr": "sum(aerospike_xdr_in_queue{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total In Queue"
    }
   ]
  },
  {
   "title": "DC Nodes",
   "type": "stat",
   "description": "Number of nodes in the destination DC as seen by XDR (Average)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_xdr_nodes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\", dc=~\"$dc\"}) by (dc)",
     "legendFormat": "{{dc}}"
    }
   ]
  },
  { "title": "Detailed Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "XDR throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "XDR THROUGHPUT" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_throughput{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Throughput {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Success",
   "type": "graph",
   "description": "Number of records successfully shipped",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "XDR  SHIP SUCCESS" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_success{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Success {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Abandoned",
   "type": "graph",
   "description": "Number of ships abandoned",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "XDR  SHIP ABANDONED" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_abandoned{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Abandoned {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Not Found",
   "type": "graph",
   "description": "Number of XDR local read not found",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "XDR NOT FOUND" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_not_found{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Not found {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Filtered Out",
   "type": "graph",
   "description": "How many records are skipped after XDR reading the record locally but before putting them on wire",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "XDR  FILTERED OUT" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_filtered_out{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Filtered out {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Retry Connection Reset",
   "type": "graph",
   "description": "Number of retries due to connection reset",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "XDR  RETRY CONN RESET" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_retry_conn_reset{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Retry Conn Reset {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Retry Destination",
   "type": "graph",
   "description": "Number of retries due to temporary error from destination",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "XDR  RETRY DESTINATION" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_retry_dest{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Retry Destination {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Hot Keys",
   "type": "graph",
   "description": "Number of times a record write is skipped from processing because that record is already pending processing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "XDR HOT KEYS" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_hot_keys{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Hot keys {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "In Progress",
   "type": "graph",
   "description": "Number of XDR processing record in progress",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "XDR IN-PROGRESS" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_in_progress{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "In Progress {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "In Queue",
   "type": "graph",
   "description": "Number of records waiting to be processed in in-memory transaction queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "XDR IN-QUEUE" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_in_queue{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "In queue {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "description": "It signifies how much behind the destination is compared to the source. In other words, so much time worth of data is yet to be shipped from source to destination",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "XDR LAG" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_lag{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Lag {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Lap μs",
   "type": "graph",
   "description": "Time taken to process records across partitions in one lap. A higher number indicates slowness of source in processing the records.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "XDR LAP μS" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_lap_us{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Lap μs {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Recoveries",
   "type": "graph",
   "description": "Number of partitions that are recovered by reducing the primary index of that partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "XDR  RECOVERIES" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_recoveries{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
     "legendFormat": "Recoveries {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Recoveries Pending",
   "type": "graph",
   "description": "Number of recoveries that are currently pending",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "XDR RECOVERIES PENDING" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_recoveries_pending{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Recoveries pending {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Latency ms",
   "type": "graph",
   "description": "Average network latency for the successfully shipped records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "XDR AVG SHIP LATENCY MS" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_latency_ms{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Latency ms {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Avg Compression Ratio",
   "type": "graph",
   "description": "Average XDR compression ratio",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short", "label": "XDR AVG COMPRESSION RATIO" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_compression_ratio{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Avg compression ratio {{service}} {{dc}}"
    }
   ]
  },
  {
   "title": "Uncompressed Pct",
   "type": "graph",
   "description": "How much % of records are not compressed because they are below the compression threshold",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "XDR AVG UNCOMPRESSED PCT" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_uncompressed_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
     "legendFormat": "Uncompressed pct {{service}} {{dc}}"
    }
   ]
  }
 ]
}